import { ToolCategory } from './types';

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'pdf',
    name: 'PDF Tools',
    icon: 'FileText',
    tools: [
      {
        id: 'pdf-merge',
        name: 'Merge PDF',
        description: 'Combine multiple PDFs into one document',
        icon: 'Combine',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-split',
        name: 'Split PDF',
        description: 'Extract pages or split PDF into multiple files',
        icon: 'Split',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-compress',
        name: 'Compress PDF',
        description: 'Reduce PDF file size without losing quality',
        icon: 'Minimize2',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-edit',
        name: 'Edit PDF',
        description: 'Add text, images, and annotations to PDF',
        icon: 'Edit',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-sign',
        name: 'Sign PDF',
        description: 'Add digital signatures to PDF documents',
        icon: 'PenTool',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-protect',
        name: 'Protect PDF',
        description: 'Add password protection to PDF files',
        icon: 'Lock',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-unlock',
        name: 'Unlock PDF',
        description: 'Remove password protection from PDF files',
        icon: 'Unlock',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
    ],
  },
  {
    id: 'excel',
    name: 'Excel Tools',
    icon: 'Table',
    tools: [
      {
        id: 'excel-merge',
        name: 'Merge Excel',
        description: 'Combine multiple Excel files into one',
        icon: 'Combine',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'excel-split',
        name: 'Split Excel',
        description: 'Split Excel file by sheets or rows',
        icon: 'Split',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'excel-format',
        name: 'Format Excel',
        description: 'Apply formatting and styling to Excel',
        icon: 'Palette',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'excel-clean',
        name: 'Clean Data',
        description: 'Remove duplicates and clean Excel data',
        icon: 'Sparkles',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'excel-to-csv',
        name: 'Excel to CSV',
        description: 'Convert Excel files to CSV format',
        icon: 'FileSpreadsheet',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'csv-to-excel',
        name: 'CSV to Excel',
        description: 'Convert CSV files to Excel format',
        icon: 'FileSpreadsheet',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
    ],
  },
  {
    id: 'word',
    name: 'Word Tools',
    icon: 'FileText',
    tools: [
      {
        id: 'word-merge',
        name: 'Merge Word',
        description: 'Combine multiple Word documents',
        icon: 'Combine',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'word-split',
        name: 'Split Word',
        description: 'Split Word document by sections',
        icon: 'Split',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'word-find-replace',
        name: 'Find & Replace',
        description: 'Find and replace text in Word documents',
        icon: 'Search',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'word-format',
        name: 'Format Word',
        description: 'Apply consistent formatting to Word',
        icon: 'Palette',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
    ],
  },
  {
    id: 'converters',
    name: 'Converters',
    icon: 'RefreshCw',
    tools: [
      {
        id: 'pdf-to-word',
        name: 'PDF to Word',
        description: 'Convert PDF to editable Word document',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-to-excel',
        name: 'PDF to Excel',
        description: 'Convert PDF tables to Excel',
        icon: 'ArrowRight',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-to-ppt',
        name: 'PDF to PowerPoint',
        description: 'Convert PDF to PowerPoint presentation',
        icon: 'ArrowRight',
        freePlan: false,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        description: 'Convert PDF pages to JPG images',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'pdf-to-txt',
        name: 'PDF to Text',
        description: 'Extract text from PDF files',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'word-to-pdf',
        name: 'Word to PDF',
        description: 'Convert Word documents to PDF',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'excel-to-pdf',
        name: 'Excel to PDF',
        description: 'Convert Excel spreadsheets to PDF',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG to PDF',
        description: 'Convert images to PDF format',
        icon: 'ArrowRight',
        freePlan: true,
        proPlan: true,
        enterprisePlan: true,
      },
    ],
  },
];
